
[package]
name = "cgg"
version = "0.1.2"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
uuid = { version = "1.16.0", features = ["v4"] }
